apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular
  labels:
    app: angular
spec:
  replicas: 2
  selector:
    matchLabels:
      app: angular
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: angular
        tier: frontend
    spec:
      containers:
      - name: angular
        image: eckhardo/angular
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            port: 80
            path: /
          periodSeconds: 1000
          initialDelaySeconds: 15
          timeoutSeconds: 5
