export enum EquipmentType {
  GP = 'GENERAL PURPOSE',
  HC = 'GENERAL PURPOSE HIGH CUBE',
  RH = 'REEFER HIGH CUBE',
  RF = 'REEFER',
  FR = 'FLATRACK',
  FH = 'FLATRACK HIGH CUBE',
  OH = 'OPENTOP HIGH CUBE',
  PL = 'PLATFORM',
  TK = 'TANK',
  BK = 'BULK CONTAINER',
  VE = 'VENTILATED',
  GN = 'GENSET NOSE MOUNT',
  GU = 'GENSET UNDERSLUNG',
  CH = 'CHASSIS',
  DF = 'DEFAULT'
}
